name: Build Hook

on:
  push:
    branches: [ hook ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Meson
        run: pip install meson

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure HID
        run: meson setup build/hid hid --buildtype release --backend vs2022

      - name: Compile HID
        run: meson compile -C build/hid -j 0

      - name: Configure Hook
        run: meson setup build/hook . --buildtype release --backend vs2022

      - name: Compile Hook
        run: meson compile -C build/hook -j 0

      - name: Move Files
        run: |
          mkdir -p build/release
          mv build/hid/hid_win10.* build/release/
          mv build/hid/hid_win11.* build/release/
          mv build/hook/rivet_hook.* build/release/

      - uses: actions/upload-artifact@v4
        with:
          name: 'release'
          path: 'build/release'
