# SPDX-FileCopyrightText: 2026 Neptuwunium <ada@chronovore.dev>
#
# SPDX-License-Identifier: EUPL-1.2

name: Build

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable, develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Meson
        run: pip install meson

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure Hook
        run: meson setup build . --buildtype release --debug --backend vs2022

      - name: Compile Hook
        run: meson compile -C build -j 0

      - name: Move Files
        run: |
          mkdir -p build/rivet_hook
          mv build/rivet_hook.dll build/rivet_hook/
          mv build/rivet_hook.pdb build/rivet_hook/
          mv build/subprojects/rivet_hid/hid.dll build/rivet_hook/
          mv build/subprojects/rivet_hid/hid.pdb build/rivet_hook/
          mv build/subprojects/rivet_hid/hid_win10.dll build/rivet_hook/
          mv build/subprojects/rivet_hid/hid_win10.pdb build/rivet_hook/

      - uses: actions/upload-artifact@v4
        with:
          name: 'rivet_hook'
          path: 'build/rivet_hook'
