# SPDX-FileCopyrightText: 2026 Neptuwunium <ada@chronovore.dev>
#
# SPDX-License-Identifier: EUPL-1.2

name: Build

on:
  push:
    branches: [ stable ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        buildenv: [vs, mingw]
        buildtype: [debug, release]
        loader: [true, false]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Meson
        run: pip install meson ninja

      - name: Install NASM
        run: choco install nasm

      - name: Setup MSBuild
        if: matrix.buildenv == 'vs'
        uses: microsoft/setup-msbuild@v2

      # NOTE: build type release has a deadlock when the hook gets unloaded
      # need to figure out why.
      - name: Configure Hook (MSVC)
        if: matrix.buildenv == 'vs'
        run: meson setup build . --buildtype ${{ matrix.buildtype }} --debug --vsenv

      - name: Configure Hook (MinGW)
        if: matrix.buildenv == 'mingw'
        run: meson setup build . --buildtype ${{ matrix.buildtype }} --debug -Dloader_only=${{ matrix.loader }}

      - name: Compile Hook
        run: meson compile -C build -j 0

      - name: Move Files
        run: |
          mkdir -p build/rivet_hook
          mv build/rivet_hook.dll build/rivet_hook/
          mv build/subprojects/hid_hook/hid.dll build/rivet_hook/
          mv build/subprojects/hid_hook/hid_win10.dll build/rivet_hook/

      - name: Move Debug Files
        if: matrix.buildenv == 'vs'
        run: |
          mv build/rivet_hook.pdb build/rivet_hook/
          mv build/subprojects/hid_hook/hid.pdb build/rivet_hook/
          mv build/subprojects/hid_hook/hid_win10.pdb build/rivet_hook/

      - uses: actions/upload-artifact@v4
        if: matrix.loader == 'false'
        with:
          name: 'rivet_hook-${{ matrix.buildtype }}-${{ matrix.buildenv }}'
          path: 'build/rivet_hook'

      - uses: actions/upload-artifact@v4
        if: matrix.loader == 'true'
        with:
          name: 'rivet_loader-${{ matrix.buildtype }}-${{ matrix.buildenv }}'
          path: 'build/rivet_hook'
